name: Build & Deploy Laravel Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Build the Laravel image (multi‑stage Dockerfile)
      - name: Build Laravel image
        run: docker build -t hello-laravel -f docker/php/Dockerfile .

      # 2️⃣ Save & compress for scp transfer
      - name: Save & compress Docker image
        run: docker save hello-laravel | gzip > hello-laravel.tar.gz

      # 3️⃣ Sanity‑check artefacts exist
      - name: Verify local files
        run: |
          set -e
          [ -f docker-compose.yml ]              || { echo "docker-compose.yml missing"; exit 1; }
          [ -f docker/nginx/default.conf ]       || { echo "Nginx conf missing"; exit 1; }
          [ -f hello-laravel.tar.gz ]            || { echo "Image archive missing"; exit 1; }

      # 4️⃣ Upload compose file, Nginx config and image to EC2
      - name: Upload artefacts to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host:       ${{ secrets.HOST }}
          username:   ${{ secrets.USERNAME }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,docker/nginx/default.conf,hello-laravel.tar.gz"
          target: /home/${{ secrets.USERNAME }}/deploy
          overwrite: true

      # 5️⃣ SSH → re‑create .env from secret, load image, start stack
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:       ${{ secrets.HOST }}
          username:   ${{ secrets.USERNAME }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          envs:       LARAVEL_ENV
          script: |
            set -e
            mkdir -p $HOME/deploy

            # --- write .env from GitHub secret ---
            cat <<'EOF' > $HOME/deploy/.env
             ${{ secrets.LARAVEL_ENV }}
             EOF

            cd $HOME/deploy

            echo "=== Ensure Docker & Compose v2 are present ==="
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
            fi
            if ! docker compose version >/dev/null 2>&1; then
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -fsSL \
                https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 \
                -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            echo "=== Load the new Laravel image ==="
            gunzip -c hello-laravel.tar.gz | sudo docker load

            echo "=== Bring containers up (or recreate) ==="
            sudo docker compose -f docker-compose.yml up -d --pull=never --remove-orphans

            echo "=== Prune dangling images ==="
            sudo docker image prune -f

            echo "=== Show container status ==="
            sudo docker compose ps
