name: Build & Deploy Laravel Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Build the Laravel image (multi‑stage Dockerfile)
      - name: Build Laravel image
        run: docker build -t hello-laravel -f docker/php/Dockerfile .

      # 2️⃣ Save & compress for scp transfer (~80 MB after gzip)
      - name: Save & compress Docker image
        run: docker save hello-laravel | gzip > hello-laravel.tar.gz

      # 3️⃣ Verify repo contains the deploy artefacts we expect
      - name: Verify local files before upload
        run: |
          echo "Repo tree:" && ls -R
          echo "Checking required files…"
          [ -f docker-compose.prod.yml ] || { echo "docker-compose.prod.yml missing"; exit 1; }
          [ -f docker/nginx/default.conf ] || { echo "Nginx conf missing"; exit 1; }
          [ -f hello-laravel.tar.gz ] || { echo "Image archive missing"; exit 1; }

      # 4️⃣ Copy compose file, nginx config, .env & image to EC2
      - name: Upload artefacts to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            docker-compose.prod.yml,
            docker/nginx/default.conf,
            .env,
            hello-laravel.tar.gz
          target: /home/${{ secrets.USERNAME }}/deploy
          overwrite: true

      # (Optional) ─ copy any other project files you want on the VM
      # e.g. cron jobs, scripts, etc.

      # 5️⃣ SSH in, load image, & start / update the stack
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd $HOME/deploy

            echo "=== Ensure Docker & Compose v2 are present ==="
            if ! command -v docker >/dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER
            fi
            if ! docker compose version >/dev/null 2>&1; then
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -sSL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 \
                   -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            echo "=== Load the new Laravel image ==="
            gunzip -c hello-laravel.tar.gz | docker load

            echo "=== Bring containers up (or recreate) ==="
            docker compose -f docker-compose.prod.yml up -d --pull=never --remove-orphans

            echo "=== Prune dangling images ==="
            docker image prune -f

            echo "=== Show container status ==="
            docker compose ps
